"""Verlauf aktualisiert, faelschlich betrag. in ereignis umgewandelt

Revision ID: 28bd7f149530
Revises: 85e6b16a6401
Create Date: 2025-12-02 22:47:11.806835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28bd7f149530'
down_revision = '85e6b16a6401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verlauf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datum', sa.Date(), nullable=False))
        batch_op.alter_column('ereignis',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('betrag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verlauf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('betrag', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.alter_column('ereignis',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('datum')

    # ### end Alembic commands ###
