"""Add pdf_path to rechnung

Revision ID: 3748fcb84de0
Revises: 94410bf02435
Create Date: 2025-11-29 15:00:27.798503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3748fcb84de0'
down_revision = '94410bf02435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rechnung', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_path', sa.String(length=512), nullable=True))
        batch_op.create_index(batch_op.f('ix_rechnung_pdf_path'), ['pdf_path'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rechnung', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rechnung_pdf_path'))
        batch_op.drop_column('pdf_path')

    # ### end Alembic commands ###
