"""add table rechnung

Revision ID: 5113d4e8aa62
Revises: cd756ec9f36e
Create Date: 2025-11-03 23:08:16.376948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5113d4e8aa62'
down_revision = 'cd756ec9f36e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rechnung',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('art', sa.Enum('ERSTRECHNUNG', 'MAHNUNG', 'STORNO', name='rechnungsartenum', native_enum=False), nullable=False),
    sa.Column('rechnungsdatum', sa.Date(), nullable=False),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('betrag', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rechnung')
    # ### end Alembic commands ###
