"""Verlauf hinzugefügt als neue Tabelle

Revision ID: 85e6b16a6401
Revises: 89a14b354028
Create Date: 2025-12-02 22:32:11.262102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e6b16a6401'
down_revision = '89a14b354028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verlauf',
    sa.Column('ereignis', sa.Text(), nullable=True),
    sa.Column('betrag', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('auftrag_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['auftrag_id'], ['auftrag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verlauf', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verlauf_auftrag_id'), ['auftrag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verlauf', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verlauf_auftrag_id'))

    op.drop_table('verlauf')
    # ### end Alembic commands ###
