"""add gesendet_datum_to_rechnung

Revision ID: 89a14b354028
Revises: b35f399fe449
Create Date: 2025-11-30 16:38:26.727578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a14b354028'
down_revision = 'b35f399fe449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rechnung', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gesendet_datum', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_rechnung_gesendet_datum'), ['gesendet_datum'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rechnung', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rechnung_gesendet_datum'))
        batch_op.drop_column('gesendet_datum')

    # ### end Alembic commands ###
