"""Add status to Rechnung

Revision ID: 94410bf02435
Revises: cfc7aa1cf98e
Create Date: 2025-11-24 08:34:19.531201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94410bf02435'
down_revision = 'cfc7aa1cf98e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rechnung', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('CREATED', 'SENT', 'CANCELED', name='rechnungsstatusenum', native_enum=False), server_default='CREATED', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rechnung', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
