"""Add is_inquired field to auftrag

Revision ID: acd0dd9d8d8f
Revises: c26639f27a5a
Create Date: 2025-12-07 17:33:59.222733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd0dd9d8d8f'
down_revision = 'c26639f27a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auftrag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_inquired', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auftrag', schema=None) as batch_op:
        batch_op.drop_column('is_inquired')

    # ### end Alembic commands ###
