"""initial schema

Revision ID: b35f399fe449
Revises: 
Create Date: 2025-11-29 15:39:41.182953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35f399fe449'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adresse',
    sa.Column('strasse', sa.String(length=120), nullable=False),
    sa.Column('hausnummer', sa.String(length=20), nullable=False),
    sa.Column('plz', sa.String(length=10), nullable=False),
    sa.Column('ort', sa.String(length=120), nullable=False),
    sa.Column('distanz', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('behoerde',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('adresse_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['adresse_id'], ['adresse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bestattungsinstitut',
    sa.Column('kurzbezeichnung', sa.String(length=80), nullable=False),
    sa.Column('firmenname', sa.String(length=200), nullable=False),
    sa.Column('adresse_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('anschreibbar', sa.Boolean(), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('rechnungadress_modus', sa.Enum('INSTITUT', 'INSTITUT_WEITERLEITUNG', 'ANGEHOERIGE', name='rechnungsadressmodus'), server_default='INSTITUT', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['adresse_id'], ['adresse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kurzbezeichnung')
    )
    op.create_table('patient',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('geburtsname', sa.String(length=120), nullable=True),
    sa.Column('vorname', sa.String(length=120), nullable=False),
    sa.Column('geburtsdatum', sa.Date(), nullable=False),
    sa.Column('geschlecht', sa.Enum('MAENNLICH', 'WEIBLICH', 'DIVERS', 'UNBEKANNT', name='geschlechtenum', native_enum=False), nullable=False),
    sa.Column('meldeadresse_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meldeadresse_id'], ['adresse.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_index('ix_patient_geburtsdatum', ['geburtsdatum'], unique=False)
        batch_op.create_index('ix_patient_name_vorname', ['name', 'vorname'], unique=False)

    op.create_table('angehoeriger',
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('vorname', sa.String(length=120), nullable=True),
    sa.Column('geschlecht', sa.Enum('MAENNLICH', 'WEIBLICH', 'DIVERS', 'UNBEKANNT', name='geschlechtenum', native_enum=False), nullable=True),
    sa.Column('verwandtschaftsgrad', sa.String(length=80), nullable=True),
    sa.Column('telefonnummer', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('adresse_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['adresse_id'], ['adresse.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('angehoeriger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_angehoeriger_patient_id'), ['patient_id'], unique=False)

    op.create_table('auftrag',
    sa.Column('auftragsnummer', sa.Integer(), nullable=True),
    sa.Column('auftragsdatum', sa.Date(), nullable=False),
    sa.Column('auftragsuhrzeit', sa.Time(), nullable=False),
    sa.Column('kostenstelle', sa.Enum('ANGEHOERIGE', 'BESTATTUNGSINSTITUT', 'BEHOERDE', 'UNBEKANNT', name='kostenstelleenum', native_enum=False), nullable=False),
    sa.Column('mehraufwand', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('READY', 'WAIT', 'TODO', 'SENT', 'DONE', name='auftragsstatusenum', native_enum=False), nullable=False),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('auftragsadresse_id', sa.Integer(), nullable=False),
    sa.Column('bestattungsinstitut_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['auftragsadresse_id'], ['adresse.id'], ),
    sa.ForeignKeyConstraint(['bestattungsinstitut_id'], ['bestattungsinstitut.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auftragsnummer')
    )
    with op.batch_alter_table('auftrag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auftrag_bestattungsinstitut_id'), ['bestattungsinstitut_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auftrag_patient_id'), ['patient_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_auftrag_status'), ['status'], unique=False)

    op.create_table('auftrag_behoerde',
    sa.Column('auftrag_id', sa.Integer(), nullable=False),
    sa.Column('behoerde_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auftrag_id'], ['auftrag.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['behoerde_id'], ['behoerde.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('auftrag_id', 'behoerde_id')
    )
    op.create_table('rechnung',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('art', sa.Enum('ERSTRECHNUNG', 'MAHNUNG', 'STORNO', name='rechnungsartenum', native_enum=False), nullable=False),
    sa.Column('rechnungsdatum', sa.Date(), nullable=False),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('betrag', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'SENT', 'CANCELED', name='rechnungsstatusenum', native_enum=False), server_default='CREATED', nullable=False),
    sa.Column('pdf_path', sa.String(length=512), nullable=True),
    sa.Column('auftrag_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['auftrag_id'], ['auftrag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rechnung', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rechnung_auftrag_id'), ['auftrag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rechnung_pdf_path'), ['pdf_path'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rechnung', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rechnung_pdf_path'))
        batch_op.drop_index(batch_op.f('ix_rechnung_auftrag_id'))

    op.drop_table('rechnung')
    op.drop_table('auftrag_behoerde')
    with op.batch_alter_table('auftrag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auftrag_status'))
        batch_op.drop_index(batch_op.f('ix_auftrag_patient_id'))
        batch_op.drop_index(batch_op.f('ix_auftrag_bestattungsinstitut_id'))

    op.drop_table('auftrag')
    with op.batch_alter_table('angehoeriger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_angehoeriger_patient_id'))

    op.drop_table('angehoeriger')
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_index('ix_patient_name_vorname')
        batch_op.drop_index('ix_patient_geburtsdatum')

    op.drop_table('patient')
    op.drop_table('bestattungsinstitut')
    op.drop_table('behoerde')
    op.drop_table('adresse')
    # ### end Alembic commands ###
