"""add wait_due_date to auftrag

Revision ID: c26639f27a5a
Revises: bf013bf0cf63
Create Date: 2025-12-06 21:54:01.546609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26639f27a5a'
down_revision = 'bf013bf0cf63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auftrag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wait_due_date', sa.Date(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('READY', 'WAIT', 'TODO', 'SENT', 'DONE', 'PRINT', 'INQUIRY', name='auftragsstatusenum', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auftrag', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('READY', 'WAIT', 'TODO', 'SENT', 'DONE', 'PRINT', 'INQUIRY', name='auftragsstatusenum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('wait_due_date')

    # ### end Alembic commands ###
