"""initial migration

Revision ID: cd756ec9f36e
Revises: 
Create Date: 2025-11-03 22:43:26.838645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd756ec9f36e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adresse', schema=None) as batch_op:
        batch_op.drop_column('geo_query')
        batch_op.drop_column('geo_confidence')
        batch_op.drop_column('geo_lon')
        batch_op.drop_column('geo_raw')
        batch_op.drop_column('geo_provider')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('geo_lat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adresse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geo_lat', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('geo_provider', sa.VARCHAR(length=40), nullable=True))
        batch_op.add_column(sa.Column('geo_raw', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('geo_lon', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('geo_confidence', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('geo_query', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
