"""Add rechnungsadress_modus to Betattungsinstitute

Revision ID: cfc7aa1cf98e
Revises: 87aae988e92c
Create Date: 2025-11-06 16:58:13.834383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfc7aa1cf98e'
down_revision = '87aae988e92c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bestattungsinstitut', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rechnungadress_modus', sa.Enum('INSTITUT', 'INSTITUT_WEITERLEITUNG', 'ANGEHOERIGE', name='rechnungsadressmodus'), server_default='INSTITUT', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bestattungsinstitut', schema=None) as batch_op:
        batch_op.drop_column('rechnungadress_modus')

    # ### end Alembic commands ###
